# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField()),
                ('sign_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user_log_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_details.Sign_Up')),
            ],
        ),
    ]
